import firebase from 'firebase/compat/app';
import 'firebase/compat/firestore';

export type Timestamp = firebase.firestore.Timestamp;

export interface Break {
    name: string;
    startTime: string; // "HH:mm"
    endTime: string; // "HH:mm"
}

export interface PlanningGroupSection {
    l3Id: string;
    l3Name: string;
    l4Id: string;
    l4Name: string;
    l5Id: string;
    l5Name: string;
    path: string;
}

export interface PlanningGroup {
    id: string;
    code: string;
    name: string;
    description: string;
    assignedSections: PlanningGroupSection[];
    createdBy: { uid: string; name: string };
    createdAt: Timestamp;
    updatedAt?: Timestamp;
}

export interface MaintenancePlan {
  id: string; // Firestore document ID
  planId: string; // e.g., PM0000001
  planName: string;
  
  // Scheduling
  year?: number;
  week?: number;
  scheduledStartDate: string; // YYYY-MM-DD
  scheduledEndDate: string; // YYYY-MM-DD
  durationDays?: number;

  status: 'OPEN' | 'IN_PROGRESS' | 'SCHEDULED' | 'COMPLETED' | 'CANCELLED' | 'CLOSED';
  createdBy: { uid: string; name: string };
  createdAt: Timestamp;
  workStartTime?: string; // e.g., "08:00"
  workEndTime?: string; // e.g., "17:00"
  breaks?: Break[]; // Max 4 breaks
  approvals?: {
      stage1?: { uid: string; name: string; date: string };
      stage2?: { uid: string; name: string; date: string };
  };

  // Technical Metadata (for filtering)
  disciplineCode?: string;
  disciplineName?: string;
  intervalCode?: string;
  intervalName?: string;

  // Hierarchy Context
  allocationLevel3Id?: string;
  allocationLevel3Name?: string;
  allocationLevel4Id?: string;
  allocationLevel4Name?: string;
  allocationLevel5Id?: string;
  allocationLevel5Name?: string;
}

import type { RiskAssessmentItem } from './she_types';

export interface MasterPlanTask {
    id: string;
    taskId: string; // e.g. T01
    taskName: string;
    description: string;
    estimatedDurationHours: number;
    discipline: string;
    taskTypeCategory: string;
    taskTypeModeCode: string;
    taskTypeModeName: string;
    maintenanceTypeCode: string;
    maintenanceTypeName: string;
    requiredSpares?: SparePart[];
    requiredServices?: ServiceItem[];
    riskAssessments?: RiskAssessmentItem[];
    createdAt?: Timestamp;
    createdBy?: { uid: string; name: string };
    // Added isCritical property to resolve TypeScript error in MasterPlanTaskDetail.tsx
    isCritical?: boolean;
    enabled?: boolean;
}

export interface MaintenanceMasterPlan {
    id: string;
    code: string; // Autogenerated: DISC_INT_STAT
    assemblyId: string;
    assemblyName: string;
    assemblyPath: string;
    disciplineCode: string;
    disciplineName: string;
    intervalCode: string;
    intervalName: string;
    statusCode: string;
    statusName: string;
    enabled: boolean;
    activeFrom: string | 'Indefinite';
    createdAt: Timestamp;
    createdBy: { uid: string; name: string };
    tasks?: MasterPlanTask[];
    
    // New Management Fields
    lastCalled?: string | null;
    enabledAuto?: boolean;
    resetTag?: boolean;
}

export interface MaintenanceType {
  code: string; // Document ID
  name: string;
  description: string;
  enabled: boolean;
  color?: string;
}

export interface MaintenanceInterval {
  code: string; // Document ID
  name: string;
  description: string;
  enabled: boolean;
  color?: string;
}

export interface MaintenanceDiscipline {
  code: string; // Document ID
  name: string;
  description: string;
  enabled: boolean;
  color?: string;
}

export interface MaintenanceStatus {
  code: string; // Document ID
  name: string;
  description: string;
  enabled: boolean;
  color?: string;
}

export interface NotificationSource {
  code: string; // Document ID
  name: string;
  description: string;
  enabled: boolean;
}

export interface FailureMode {
  id: string; // Auto-generated Document ID
  name: string;
  description: string;
  category: 'Man' | 'Machine' | 'Method' | 'Material' | 'Environment';
  enabled: boolean;
}

export interface SolutionMode {
  id: string; // Auto-generated Document ID
  name: string;
  description: string;
  enabled: boolean;
  category: 'Corrective' | 'Preventive' | 'Procedural' | 'Analytical' | 'No Action';
}

export interface RiskCategory {
  code: string; // Document ID, e.g., PERF
  name: string;
  description: string;
  enabled: boolean;
  color?: string;
}

export interface RiskSubcategory {
  code: string; // Document ID, e.g., PERF-DOWN
  name: string;
  description: string;
  enabled: boolean;
}

export interface WorkRequest {
  id: string; // Firestore document ID
  wrId: string; // Sequential human-readable ID
  title: string;
  description: string;
  assemblyPath: string; // Firestore path to the assembly
  assemblyName: string;
  assemblyCode: string;
  
  // Location denormalized from asset
  allocationLevel1Id?: string;
  allocationLevel1Name?: string;
  allocationLevel2Id?: string;
  allocationLevel2Name?: string;
  allocationLevel3Id?: string;
  allocationLevel3Name?: string;
  allocationLevel4Id?: string;
  allocationLevel4Name?: string;
  allocationLevel5Id?: string;
  allocationLevel5Name?: string;
  allocationLevel6Id?: string; // This is the asset ID
  allocationLevel6Name?: string; // This is the asset name
  allocationLevel7Id?: string; // This is the assembly ID
  allocationLevel7Name?: string; // This is the assembly name

  createdBy: {
    uid: string;
    name: string;
  };
  createdAt: Timestamp; // Firestore Timestamp
  status: 'CREATED' | 'CONVERTED' | 'CLOSED' | 'REJECTED' | 'CANCELLED';
  
  // Timestamps for KPIs
  convertedAt?: Timestamp;
  closedAt?: Timestamp;
  workOrderId?: string;

  // New fields
  requestDate: string; // YYYY-MM-DD
  raisedBy: {
    uid: string;
    name: string;
  };
  tagSource: string;
  
  impactCategoryCode: string;
  impactCategoryName: string;
  impactSubcategoryCode: string;
  impactSubcategoryName: string;
  impactSubcategoryDescription: string;

  // Added for closing/converting
  closedBy?: { uid: string; name: string };
  convertedBy?: { uid: string; name: string };
  cancellationReason?: string;

  // Added for editing
  updatedAt?: Timestamp;
  updatedBy?: { uid: string; name: string };
}

export type WorkOrderStatus = 'OPEN' | 'IN_PROGRESS' | 'SCHEDULED' | 'COMPLETED' | 'CLOSED' | 'CANCELLED';

export interface WorkOrder {
  id: string; // Firestore document ID
  woId: string; // Sequential human-readable ID, e.g., WO00000001
  workRequestRef: string; // Path to the original WorkRequest
  wrId: string; // Copied from WorkRequest for reference

  title: string;
  description: string;
  assemblyPath: string;
  assemblyName: string;
  assemblyCode: string;

  // Location denormalized from asset
  allocationLevel1Id?: string;
  allocationLevel1Name?: string;
  allocationLevel2Id?: string;
  allocationLevel2Name?: string;
  allocationLevel3Id?: string;
  allocationLevel3Name?: string;
  allocationLevel4Id?: string;
  allocationLevel4Name?: string;
  allocationLevel5Id?: string;
  allocationLevel5Name?: string;
  allocationLevel6Id?: string; // This is the asset ID
  allocationLevel6Name?: string; // This is the asset name
  allocationLevel7Id?: string; // This is the assembly ID
  allocationLevel7Name?: string; // This is the assembly name

  createdAt: Timestamp; // Firestore Timestamp
  createdBy: { uid: string; name: string }; // User who converted the WR
  status: WorkOrderStatus;

  // New fields for Work Orders
  assignedTo?: { uid: string; name: string };
  maintenanceType?: string; // e.g., PM, CM
  
  scheduledStartDate?: string | null; // YYYY-MM-DD
  scheduledEndDate?: string | null; // YYYY-MM-DD
  pmNumber?: string | null; // Human-readable PM ID from MaintenancePlan
  
  actualStartDate?: Timestamp;
  actualCompletionDate?: Timestamp;

  // Copied from WR for context
  raisedBy: { uid: string; name: string };
  tagSource: string;
  impactCategoryName: string;
  impactSubcategoryName: string;
  impactSubcategoryDescription: string;
}

export interface SparePart {
    materialId: string;
    materialCode: string;
    name: string;
    quantity: number;
    uom: string;
    warehouseId?: string;
    warehouseName?: string;
    warehousePath?: string;
    reservationId?: string;
}

export interface ServiceItem {
    id: string;
    categoryId: string;
    categoryName: string;
    categoryDescription: string;
    subcategoryId: string;
    subcategoryName: string;
    subcategoryDescription: string;
    supplier: string;
    hasFramework: boolean;
    frameworkRef?: string;
    availabilityStatus: 'Not Contacted' | 'Available' | 'Not Available';
    tentativeDate?: string;
    hourlyRate?: number;
    hours?: number;
    overtimeRate?: number;
    overtimeHours?: number;
}

export interface Reservation {
  id?: string; // Firestore doc ID
  reservationId: string; // e.g., RES0000001
  maintenancePlanId?: string; // e.g., MP000001
  workOrderId: string;
  workOrderPath: string;
  taskId: string;
  taskPath: string;
  materialId: string;
  materialCode: string;
  materialName: string;
  quantity: number;
  uom: string;
  warehouseId: string;
  warehouseName: string;
  level_1_id: string;
  level_2_id: string;
  level_3_id: string;
  level_4_id: string;
  status: 'ACTIVE' | 'ISSUED' | 'CANCELLED' | 'RESERVED' | 'ORDERED' | 'LOCKED' | 'PROCESSED' | 'PR REQUIRED' | 'PR RAISED';
  reservedBy: { uid: string; name: string };
  reservedAt: Timestamp;
  issuedBy?: { uid: string; name: string };
  issuedAt?: Timestamp;
  cancelledBy?: { uid: string; name: string };
  cancelledAt?: Timestamp;
}

// Added SafetyIncidentReport interface to resolve missing name error in WorkOrderTask
export interface SafetyIncidentReport {
    hazardId?: string;
    hazardName?: string;
    description: string;
    severity: 'Low' | 'Medium' | 'High';
    injuryCategoryId?: string;
    injuryId?: string;
}

export interface WorkOrderTask {
  id: string; // Firestore document ID
  taskId: string; // e.g., WO00000001-T01
  taskName: string;
  description: string;
  status: 'PENDING' | 'IN_PROGRESS' | 'COMPLETED';
  
  taskTypeCategory: string; // From SolutionMode category
  taskTypeModeCode: string; // From SolutionMode id
  taskTypeModeName: string; // From SolutionMode name
  maintenanceTypeCode: string; // From MaintenanceType code
  maintenanceTypeName: string; // From MaintenanceType name
  discipline: string; // e.g., Mechanical, Electrical

  estimatedDurationHours?: number;
  actualDurationHours?: number; // Actuals
  requiredSpares?: SparePart[];
  requiredServices?: ServiceItem[];
  
  createdAt: Timestamp; // Firestore Timestamp
  createdBy: { uid: string; name: string };
  updatedAt?: Timestamp;
  updatedBy?: { uid: string; name: string };
  completedAt?: Timestamp;

  assignedTo?: { uid: string; name: string }[];
  riskAssessments?: RiskAssessmentItem[];
  safetyIncidents?: SafetyIncidentReport[];
  completionComments?: string;
  
  // New fields for plan-based scheduling
  scheduledStartDate?: string;
  scheduledStartTime?: string;
  precedingTaskId?: string;
  isCritical?: boolean;
  isBreakin?: boolean; // If added during execution
}

/**
 * Added EnrichedTask interface to support maintenance planning views.
 * This type flattens the task with its parent work order context.
 */
export interface EnrichedTask extends WorkOrderTask {
    workOrderId: string;
    workOrderPath: string;
    woId: string;
    allocationLevel1Id?: string;
    allocationLevel1Name?: string;
    allocationLevel2Id?: string;
    allocationLevel2Name?: string;
    allocationLevel3Id?: string;
    allocationLevel3Name?: string;
    allocationLevel4Id?: string;
    allocationLevel4Name?: string;
    allocationLevel5Id?: string;
    allocationLevel5Name?: string;
    allocationLevel6Id?: string;
    allocationLevel6Name?: string;
    allocationLevel7Id?: string;
    allocationLevel7Name?: string;
    isSafetyTask?: boolean;
    originalTaskId?: string;
    ganttStartDate?: Date;
    ganttEndDate?: Date;
}

export interface SpareMetadata {
    price: number;
    leadTimeDays: number;
    name: string;
    code: string;
    bin?: string;
}