
import React, { useState, useEffect } from 'react';
import { db } from '../../../../services/firebase';
import type { WorkOrder, WorkRequest } from '../../../../types/am_types';
import Button from '../../../Button';
import 'firebase/compat/firestore';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface WorkOrderRequestDetailsProps {
  workOrder: WorkOrder;
}

const DetailItem: React.FC<{ label: string; value?: string | null }> = ({ label, value }) => (
    <div>
        <dt className="text-xs font-bold text-slate-400 uppercase tracking-wider">{label}</dt>
        <dd className="mt-1 text-sm font-medium text-slate-800 break-words">{value || '-'}</dd>
    </div>
);

const WorkOrderRequestDetails: React.FC<WorkOrderRequestDetailsProps> = ({ workOrder }) => {
    const [workRequest, setWorkRequest] = useState<WorkRequest | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [generatingPdf, setGeneratingPdf] = useState(false);

    useEffect(() => {
        if (!workOrder.workRequestRef) {
            setError('Work Request reference is missing.');
            setLoading(false);
            return;
        }

        const fetchWorkRequest = async () => {
            setLoading(true);
            setError('');
            try {
                // FIX: Use db.doc(...) instead of doc(db, ...) to align with Firebase v8 compat syntax. Imported 'doc' is not necessary.
                const wrDocRef = db.doc(workOrder.workRequestRef);
                const wrDocSnap = await wrDocRef.get();

                if (wrDocSnap.exists) {
                    setWorkRequest({ id: wrDocSnap.id, ...wrDocSnap.data() } as WorkRequest);
                } else {
                    setError('Original Work Request not found.');
                }
            } catch (err: any) {
                setError('Failed to fetch Work Request details.');
                console.error(err);
            } finally {
                setLoading(false);
            }
        };

        fetchWorkRequest();
    }, [workOrder.workRequestRef]);

    const handleDownloadPDF = async () => {
        const input = document.getElementById('printable-wo-request-card');
        if (!input) return;
        
        setGeneratingPdf(true);
        
        // Create a clone to render full height without scrollbars and apply specific print styling
        const clone = input.cloneNode(true) as HTMLElement;
        clone.style.width = '794px'; // A4 width approx at 96DPI
        clone.style.height = 'auto'; // Auto height
        clone.style.position = 'absolute';
        clone.style.top = '-10000px';
        clone.style.left = '-10000px';
        clone.style.background = 'white';
        clone.style.border = '2px solid #334155'; // Professional dark border
        clone.style.borderRadius = '8px';
        clone.style.padding = '20px';
        clone.classList.remove('shadow-sm');
        
        // Add footer
        const footer = document.createElement('div');
        footer.style.marginTop = '20px';
        footer.style.paddingTop = '10px';
        footer.style.borderTop = '1px solid #e2e8f0';
        footer.style.color = '#94a3b8';
        footer.style.fontSize = '10px';
        footer.style.display = 'flex';
        footer.style.justifyContent = 'space-between';
        footer.innerHTML = `<span>Generated by MEMS</span><span>${new Date().toLocaleString()}</span>`;
        clone.appendChild(footer);

        document.body.appendChild(clone);

        try {
            const canvas = await html2canvas(clone, {
                scale: 2,
                backgroundColor: '#ffffff',
                useCORS: true
            });
            
            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF('p', 'mm', 'a4');
            const pdfWidth = 210;
            const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
            
            pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
            pdf.save(`Original_Request_${workRequest?.wrId}.pdf`);
        } catch (err) {
            console.error("Error generating PDF:", err);
            alert("Failed to generate PDF.");
        } finally {
            document.body.removeChild(clone);
            setGeneratingPdf(false);
        }
    };

    // Styling based on Impact
    const getImpactStyle = (category: string) => {
        const cat = category.toLowerCase();
        if (cat.includes('safety')) return { border: 'border-red-600', bg: 'bg-red-50', text: 'text-red-700', badge: 'bg-red-100 text-red-800' };
        if (cat.includes('asset integrity')) return { border: 'border-orange-500', bg: 'bg-orange-50', text: 'text-orange-700', badge: 'bg-orange-100 text-orange-800' };
        if (cat.includes('compliance')) return { border: 'border-purple-600', bg: 'bg-purple-50', text: 'text-purple-700', badge: 'bg-purple-100 text-purple-800' };
        if (cat.includes('cost')) return { border: 'border-emerald-600', bg: 'bg-emerald-50', text: 'text-emerald-700', badge: 'bg-emerald-100 text-emerald-800' };
        if (cat.includes('delivery')) return { border: 'border-blue-500', bg: 'bg-blue-50', text: 'text-blue-700', badge: 'bg-blue-100 text-blue-800' };
        if (cat.includes('morale')) return { border: 'border-rose-500', bg: 'bg-rose-50', text: 'text-rose-700', badge: 'bg-rose-100 text-rose-800' };
        if (cat.includes('quality')) return { border: 'border-indigo-500', bg: 'bg-indigo-50', text: 'text-indigo-700', badge: 'bg-indigo-100 text-indigo-800' };
        
        return { border: 'border-slate-500', bg: 'bg-slate-50', text: 'text-slate-700', badge: 'bg-slate-100 text-slate-800' };
    };

    if (loading) return <div className="p-8 text-center">Loading original request details...</div>;
    if (error) return <div className="p-8 text-center text-red-500">{error}</div>;
    if (!workRequest) return <div className="p-8 text-center text-slate-500">No Work Request found.</div>;

    const impactStyle = getImpactStyle(workRequest.impactCategoryName || '');

    return (
        <div className="max-w-3xl mx-auto">
            <div className="flex justify-end mb-4">
                <Button 
                    type="button" 
                    variant="secondary" 
                    onClick={handleDownloadPDF} 
                    className="!w-auto flex items-center justify-center gap-2"
                    isLoading={generatingPdf}
                >
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    Download Request PDF
                </Button>
            </div>

            <div id="printable-wo-request-card" className="bg-white border rounded-lg overflow-hidden border-slate-200 shadow-sm flex flex-col relative">
                {/* Colored Top Boundary */}
                <div className={`h-3 w-full ${impactStyle.border.replace('border-', 'bg-')}`}></div>

                <div className="p-6 md:p-8 space-y-6">
                    {/* Header */}
                    <div className="text-center border-b border-slate-100 pb-4">
                        <h4 className="text-xs font-black text-slate-400 uppercase tracking-[0.2em] mb-2">Original Request</h4>
                        <div className="flex flex-col justify-center items-center gap-2">
                            <h1 className="text-3xl font-extrabold text-slate-800 tracking-tight">{workRequest.wrId}</h1>
                            <span className={`px-3 py-1 rounded-full text-xs font-bold uppercase border ${impactStyle.badge}`}>
                                {workRequest.status}
                            </span>
                        </div>
                        
                        {/* Hierarchy Context Bar */}
                        <div className="mt-4 flex flex-wrap justify-center gap-2 text-xs text-slate-500 bg-slate-50 p-2 rounded-lg border border-slate-100 inline-flex">
                             <span className="font-medium text-slate-700">{workRequest.allocationLevel3Name || 'Site'}</span>
                             <span className="text-slate-300">/</span>
                             <span className="font-medium text-slate-700">{workRequest.allocationLevel4Name || 'Dept'}</span>
                             <span className="text-slate-300">/</span>
                             <span className="font-medium text-slate-700">{workRequest.allocationLevel5Name || 'Section'}</span>
                        </div>

                        <div className="mt-2 text-xs text-slate-500">
                            Requested: {new Date(workRequest.requestDate).toLocaleDateString()}
                        </div>
                    </div>

                    {/* Title & Description */}
                    <div>
                        <h3 className="text-lg font-bold text-slate-900 mb-1">{workRequest.title}</h3>
                        <p className="text-sm text-slate-600 bg-slate-50 p-3 rounded-md border border-slate-100 italic">
                            "{workRequest.description}"
                        </p>
                    </div>

                    {/* Details Grid */}
                    <div className="grid grid-cols-2 gap-y-6 gap-x-8">
                        <DetailItem label="Asset" value={workRequest.allocationLevel6Name} />
                        <DetailItem label="Assembly" value={workRequest.allocationLevel7Name} />
                        
                        <DetailItem label="Raised By" value={workRequest.raisedBy.name} />
                        <DetailItem label="Tag Source" value={workRequest.tagSource} />
                    </div>

                    {/* Impact Section */}
                    <div className={`mt-6 p-4 rounded-lg border ${impactStyle.border} ${impactStyle.bg}`}>
                        <div className="flex items-center gap-2 mb-2">
                            <svg xmlns="http://www.w3.org/2000/svg" className={`h-5 w-5 ${impactStyle.text}`} viewBox="0 0 20 20" fill="currentColor">
                                <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                            </svg>
                            <h4 className={`text-sm font-bold uppercase ${impactStyle.text}`}>Impact Assessment</h4>
                        </div>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div>
                                <span className="text-xs font-semibold opacity-70 block">Category</span>
                                <span className="text-sm font-bold">{workRequest.impactCategoryName}</span>
                            </div>
                            <div>
                                <span className="text-xs font-semibold opacity-70 block">Subcategory</span>
                                <span className="text-sm font-bold">{workRequest.impactSubcategoryName}</span>
                            </div>
                            {workRequest.impactSubcategoryDescription && (
                                <div className="col-span-full mt-2 pt-2 border-t border-black/10">
                                    <p className="text-xs italic opacity-90">{workRequest.impactSubcategoryDescription}</p>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default WorkOrderRequestDetails;
